import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Tabs, TabsList } from "@radix-ui/react-tabs";
import { CustomTabsTrigger as TabsTrigger } from "@/components/custom/TabsTrigger";
import { CustomTabsContent as TabsContent } from "@/components/custom/TabsContent";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lezana",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <main>
          <Tabs className="m-4" defaultValue="geral">
            <TabsList className="flex justify-evenly">
              <TabsTrigger value="geral">Visão geral</TabsTrigger>
              <TabsTrigger value="producao">Visão produção</TabsTrigger>
            </TabsList>
            <TabsContent value="geral">Geral</TabsContent>
            <TabsContent value="producao">Produção</TabsContent>
          </Tabs>
        </main>
      </body>
    </html>
  );
}
